name: Super Linter with Email

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint codebase
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
      - name: Save Super Linter output
        run: echo "$GITHUB_ACTION_PATH" > linter_output.txt

      - name: Save Super Linter output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: linter-output
          path: linter_output.txt
