name: ShellCheck with Email

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint Shell Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: shellcheck **/*.sh > shellcheck_output.txt || true

      - name: Save ShellCheck output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: shellcheck-output
          path: shellcheck_output.txt
